apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: boutique-app
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
