apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: boutique-app
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 4004
      targetPort: 4004
