apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: boutique-app
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 4006
      targetPort: 4006
