apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: boutique-app
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      port: 4005
      targetPort: 4005
