apiVersion: v1
kind: Secret
metadata:
  name: boutique-secrets
  namespace: boutique-app
type: Opaque
stringData:
  DB_USERNAME: boutique
  DB_PASSWORD: boutique
  JWT_SECRET: change-me-jwt-secret
  DATABASE_URL: postgres://boutique:boutique@postgres-service:5432/boutiquedb
