apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  namespace: todo
  labels:
    app: todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30082
